version: "3.8"
services:
  docker-monitor:
    image: f1nnm/docker-monitor:release-0.1.1
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    restart: always

  git-manager:
    image: f1nnm/git-docker-manager:release-0.5.8
    ports:
      - "5000"
    environment:
      - WATCHED_REPO=F1nnM/server-management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    restart: always

networks:
  default:
    external: true
    name: gitdeploy

