version: "3.9"
services:
  nginx:
    build:
        context: ./src/nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./conf.d:/etc/nginx/conf.d:ro

networks:
  default:
    external: true
    name: gitdeploy

