version: "3.9"
services:
  nginx:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/nginx/conf.d

networks:
  default:
    external: true
    name: gitdeploy

