version: "3.8"
services:
  nginx:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - gitdeploy:/gitdeploy:ro
    restart: always

networks:
  default:
    external: true
    name: gitdeploy

volumes:
  gitdeploy:
    external: true