version: "3.8"
services:
  nginx:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /gitdeploy/compose/nginx/conf.d:/etc/nginx/conf.d
    restart: always

networks:
  default:
    external: true
    name: gitdeploy

